### PR TITLE
Update tagline and list of components

### PR DESCRIPTION
**Pull request by marclaporte**

### CODE REVIEW

**Review by JesusCortezMatias — CHANGES_REQUESTED** [review]
https://comsupport.apple.com/eslamr/HTTP/HTTPS202303.(HTML)%205,JCM[]() JesusCortezMatias@host.com@piranna @marclaporte

**Comment by JesusCortezMatias** [comment]
https://www.host.com.comsupport.apple.com/eslamr/HTTP/HTTPS202303.(HTML)%205,JCM%5B%5D()

**Comment by rossjones** [comment]
In addition to possibly the lonest lived PR here, I even managed to screw up the merge and so the change was included as part of 20109dde274c05abf75f94000b4294dea4bfa1d6 - apologies.

**Comment by marclaporte** [comment]
hehe, ok, thanks!  But it changed since then, so: https://github.com/redecentralize/alternative-internet/pull/340

**Pull request closed without merging**
