### PR TITLE
Add Skynet

### PR DESCRIPTION
**Pull request by jmarbach**
Add Skynet, a peer-to-peer messenger made for developers.

https://joinskynet.com

### CODE REVIEW

**Comment by talexand** [comment]
Is this FLOSS? What about this is 'alternative' internet? I don't mean to quibble but I didn't see anything on the website to differentiate it from, say, Skype.

**Comment by jmarbach** [comment]
Skynet is free software. It is not open-source at present time. The "alternative" part of Skynet is that it mechanizes the repetitive actions a developer encounters in their daily workflow, such as sharing screenshots, links to helpful resources, or files of code. Skynet makes these actions as streamlined as possible, so that the focus can stay in the conversation instead of existing tools that are clunky to use, such as screenshot sharing or file-sharing tools.

Furthermore, since Skynet is supported by a continuous deploy back-end, developers wishing to distribute their software via Skynet do not have to worry about ensuring their users' software is up-to-date.

**Comment by skybon** [comment]
@jmarbach I think you confuse [free software](http://www.gnu.org/philosophy/free-sw.html) with freeware which are distinct terms.

**Comment by talexand** [comment]
@jmarbach Those all sound like nice features maybe, but it also sounds like a sales pitch. I hate to ask, but are you in any way affiliated with this software project?

**Comment by rossjones** [comment]
Thanks for the PR, but I don't see how this is decentralized - from what I can see, looks like another silo.

Sorry.

**Pull request closed without merging**
