### PR TITLE
Added info on SoLiD

### PR DESCRIPTION
**Pull request by bblfish**

### CODE REVIEW

**Comment by bblfish** [comment]
not sure what check failed

**Comment by rossjones** [comment]
The OHLOH key isn't available to remote branches.  And you're suppose to submit a JSON file - https://github.com/redecentralize/alternative-internet/blob/master/CONTRIBUTING.md ;)

**Comment by shevski** [comment]
@deiu - perhaps you'd like to update?

**Comment by deiu** [comment]
Thanks for mentioning this issue, I didn't know about it. I'll take a look and submit a proper PR.

**Pull request closed without merging**
