### PR TITLE
Create LemonEmail.json

### PR DESCRIPTION
**Pull request by horohronos**

### CODE REVIEW

**Comment by jnv** [comment]
So many questions :smile:

FAQ

**Comment by horohronos** [comment]
Yeah, thanks for that. We've removed FAQ section until we fill in all the answers. But, I can personally answer them for you. :) I hope that the service provokes you to ask questions, not the Lorem ipsum part. 👍

**Comment by jnv** [comment]
Thanks! It would be nice to at least clarify limitations of the trial account and/or length of the trial period. 

There are much more unanswered questions about implementation of the service. You claim the service to be decentralized, which, I suppose, is guaranteed by IPFS, however, if you are the only provider, there is no source code and no protocol specification, I don't have much of a choice as a user, do I?

**Comment by Cordo-van-Saviour** [comment]
@jnv Hi Jan,

I wanted to point you to our new [Pricing Plans and FAQ page](https://lemon.email/plans/). I believe that most of the things you found unclear a month ago, will be better now.

Meanwhile, we've [open-sourced our DApp](https://github.com/DevanaLabs/lemon.email-dApp), which works as a standalone, [IPFS-hosted ](https://ipfs.io/ipns/dapp.lemon.email/#/), serverless version of Lemon Email, that anyone can host on their own. We have also made significant improvements on our landing page, for Lemon Email and DApp alike, so if anyone wanted to dive deeper into our service, that could be places to start. One last point is that we've started [three-part blog series](https://medium.com/@uros.radovanovic/when-life-gives-you-lemons-create-a-decentralized-email-system-3ae33e12290a) that describes culture and processes in Devana Labs company, and also our takes on Lemon Email project as a whole.

We are a team that takes input seriously, especially sharp but fair like yours, and act on it. Hope you'll like it if you try it out!

Cheers,
Uros

**Pull request merged**
