### PR TITLE
Update Phoenix -> Patchwork

### PR DESCRIPTION
**Pull request by clehner**
Phoenix renamed to Patchwork. It is not currently on Ohloh and the previous Ohloh data was for a different project.

### CODE REVIEW

**Comment by livmackintosh** [comment]
I think a more elegant way of managing these things could be cool :smile:

**Comment by clehner** [comment]
@livmackintosh you mean how the Ohloh data was incorrect? Or that redecentralize/alternative-internet has not been updated in 3 months?

**Comment by rossjones** [comment]
@clehner @livmackintosh It's mostly a lack of time and energy.  I merged 150 something PRs but there seemed little interest in anyone coming up with a better solution.  Would *love* to see someone build it as a better catalog with more data on each product, but personally I just don't have time.

**Comment by clehner** [comment]
@rossjones, thank you for the work you've done on this project. It has been a great resource for many people. Have you considered adding more maintainers?

**Comment by rossjones** [comment]
Have asked for help before, no takers. I think a much more manageable website might work well, the ohloh integration\approach isn't ideal.

No problem with adding people at all though.

**Comment by rossjones** [comment]
Have disabled the ohloh integration for now so that at least we can get the projects in, and then I guess we could make the JSON into a proper DB or something similar. @clehner Feel free to email me if you think you might have time to help with building an alternative.

**Pull request merged**
