### PR TITLE
Add LibreWeb

### PR DESCRIPTION
**Pull request by danger89**
Adding the libreweb.org project.

### CODE REVIEW

**Comment by Kyllingene** [comment]
Considering that the project doesn't even have hosting figured out yet, it might be a tad early.

**Comment by danger89** [comment]
Sorry, what is wrong with the hosting?

**Comment by rossjones** [comment]
Thanks for the PR @danger89

**Comment by Kyllingene** [comment]
image
The "How to deploy my site/blog" answer doesn't explain hosting the site, just fabrication of the site.

**Comment by danger89** [comment]
> The "How to deploy my site/blog" answer doesn't explain hosting the site, just fabrication of the site.

Ah maybe you misunderstand. LibreWeb is using IPFS for storage. Your site is "hosted" so stored in the IPFS network. Since LibreWeb can directly read HTML pages, similar to how a traditional website can understand HTML pages, your markdown files does *NOT* need to be transpiled into HTML. Instead LibreWeb can directly parse and show you the markdown file fully rendered.

**Comment by Kyllingene** [comment]
Sorry, I only just realized you were the developer; I had typed up a long spiel about how this clearly was going for something else, but I am obviously wrong.

I think what confused me was your wording on the website. It really seemed like your target was more-or-less a replacement Internet, and figuring out how a URL replacement would work with IPFS was my main concern. However, since this doesn't aspire to be a full replacement for the Web, it seems fairly fully-featured for what it *is* trying to be. My apologies!

**Comment by danger89** [comment]
> this doesn't aspire to be a full replacement for the Web

Well, it tries to reconsider what the Web could have been if it was fully decentralized. So no, I'm not replacing the current web 'as is'. Instead I try to build an alternative solution of the web with the latest ideas and technology, to embrace decentralization.

**Pull request merged**
